### ISSUE TITLE
Support for ISO 639-3 codes ?

### ISSUE THREAD

**Issue by anviksuteiriy** [qWici/vue-lang-code-flags#8]
Hi, we are using ISO 639-3 language codes. Can this package support them (by some modification or something) ?

**Comment by qWici** [comment]
@anviksuteiriy hi, today I will consider your proposal and answer in this topic

**Comment by qWici** [comment]
I do not see much benefit from the implementation of such functionality. Since most services or APIs use just ISO 639-1 version to indicate the language code. I also looked at the list of differences between these formats and you can easily write a format converter. Most of them differ only in the extra letter at the end, so you can remove it and also take out the different codes into a separate array.

I will also be glad to see the current statistics of the formats used in development if you have one.

@anviksuteiriy thank you for understanding!

**Comment by anviksuteiriy** [comment]
Hi Qwici/Vue-Lang-Code-Flags,

Thanks for quick response.

You're right, most of them use ISO-639-1.

I was thinking of creating a filter based on language codes I need in my
code.

Anyways thanks for reply, I appreciate you work for Vue-lang-code-flags.
